### ISSUE TITLE
Test Reset Bug

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#10]
Several events reset the testing process. We’ll want to fix these to prevent the participant from losing their progress accidentally.
 
Rotating the screen:  I imagine screen locking the phone would solve this.
Leaving the app:  Clicking away using the home button and returning via the icon brings you to the initial screen, not where you last left off.
Allowing phone display to hibernate:  Oddly enough, this only seemed to occur on one of the Nexus phones, and it wasn’t easy to replicate.

**Comment by AddictArts** [comment]
I'm having a hard time replicating leaving the app and phone display hibernate.

**Comment by sanchezdanj** [comment]
Replicating the "Leaving the App" Bug: If a participant is in the middle of the test, then presses the HOME button, and then enters the app again, the app opens to the main menu.  The app should reopon to the test screen where the participant left off, based on their progress prior to hitting the HOME button.

**Comment by AddictArts** [comment]
Hmm, for meaning using the home button and coming back has no issue. It is where I left off.

**Comment by sanchezdanj** [comment]
Things seem to be working reliably enough. Previous issues potentially due to a lack of "Uninstall" prior to the new version installs.
