### ISSUE TITLE
Motion Detection

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#12]
We need to implement a way to determine if a person is moving or not.
Currently, we have activity recognition calls to determine "STILL" but we need to verify if this will work if someone is WEARING the phone, and if the activity is disrupted by simple things such as breathing.

Need: A "debug" mode that records and reports in-real-time the results of STILL (e.g., confidence value) and the accelerometer. 

Doable?

**Comment by AddictArts** [comment]
This is in build 0.17 released
