### ISSUE TITLE
Set white noise volume first and set then do the word volume

### ISSUE THREAD

**Issue by AddictArts** [SRI-CSL/langlearn#13]
Reverse the current settings

**Comment by sanchezdanj** [comment]
Just for the sake of clarity in this issue, we want the White Noise and Word volume to be changeable concurrently, on the same screen, so you can clearly adjust the ratio of these sounds.

**Comment by AddictArts** [comment]
0.18 plays the white noise volume while adjusting the words volume. The white noise adjustment is first. When adjusting the words you can go back and re-adjust the white noise as much as you need to. Keeping them separate for simplicity and performance unless the desire is to put them together. Another issue with min max may prevent that though and separate is better for addressing that issue.
