### ISSUE TITLE
Word and White Noise Volume Min/Max Slider

### ISSUE THREAD

**Issue by mreynolds08** [SRI-CSL/langlearn#14]
- The min/max line is not viewable when adjusting the slider for the word and/or white noise volume. Such that, the line is completely obscured when at the minimum, and only completely visible when at the maximum. we should make the min/max line visible at all times.

- It would be helpful to set the slider at default at the center of the slider(.5) for white noise. That would at least alert the participant that the slider was present.

**Comment by AddictArts** [comment]
By min/max I think you mean the seek bar which adjust the volume as well. I can make the margin greater so the finger does not obscure it. It is an Android slider which has the material look, not sure how much style can be applied to it. That slider adjusts the same volume.

**Comment by AddictArts** [comment]
I can change the defaults to 0.5 but existing installs will not change. The other option is to force picking volume each time, probably not what is desired. Note that a new install can be set to that volume and exit the app. Then the user would see it at 0.5.

**Comment by AddictArts** [comment]
Part of release 0.20, the whole layout was reworked to match the newest mockup
