### ISSUE TITLE
Keyboard Memory Between Trials (Current Trial and Trial-1)

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#18]
This may, or may not, be a bug as we cannot tell yet if the behavior is linked to the app or to a specific keyboard application running on an Android device.

- There was text entry carryover from the previous trial onto the current trial (seems specifically tied to the just the most recent previous trial, not previous history trials overall). 
- Example: User responds with "she" to trial7 and submits. When typing "him" for trial8, it autofilled "she" after the first "h" keyboard press, so that the text began with "sheh."
- Specific to an LG phone

**Comment by AddictArts** [comment]
Release 0.24 will have this resolved.
Disabling the suggestions using text|textNoSuggestions
For reference:
https://stackoverflow.com/questions/3349121/how-do-i-use-inputfilter-to-limit-characters-in-an-edittext-in-android
https://stackoverflow.com/questions/5049710/disable-predictive-text-in-edittext
