### ISSUE TITLE
Test and Sleep Volume Difference

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#2]
Concern: The volume is set moderately low during sleep to allow for reasonably quiet background noise. However, this volume is far too low for test, and, particularly, DuoLingo training. 
It is imperative that people hear the words crisply during DuoLingo training, and then during sleep (but with the volume less offensively loud).

Problem: How can we just the volume, likely focused on the "Sleep" portion, such that the sound files or white noise play at an attenuated volume? a) is it possible to edit Media volume within an app? (I believe the answer is no). b) is it possible to apply some sort of attenuation or edit to the amplitude of the files for the sleep portion?

**Comment by AddictArts** [comment]
I was thinking of having a settings button that has sliders or nobs to set 3 different volumes. First is white noise, second is sleep words, and the last is test words.

**Comment by AddictArts** [comment]
Or the app can use preset volumes for each 0 to 100%. The volume is currently only set for white noise. The other is whatever your device has media volume set to when you run the app.

**Comment by AddictArts** [comment]
Currently this is implemented in the latest checkout, needs the text from the mockups and then ready for a build.

**Comment by AddictArts** [comment]
Volume control is released and in build 0.17
