### ISSUE TITLE
Add DuoLingo direct download

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#21]
Make a button to link to download DuoLingo from the LingoBoost app.

either in settings or near the bottom of the front page, a button that says "Need to download DuoLingo?"
link to : https://play.google.com/store/apps/details?id=com.duolingo

**Comment by AddictArts** [comment]
Added, will be in the next version 0.27
![device-2017-08-30-133512](https://user-images.githubusercontent.com/911906/29893824-30a02fb0-8d88-11e7-830d-03e14b1a49cd.png)
