### ISSUE TITLE
Add Splash Login Page for Inputting New User Info

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#24]
Per the email discussion, incorporate a first page that requires a username to be input. 

Remove the default user "corticalre" from the client.

**Comment by bcooper94** [comment]
Fixed in commit [46e8cc7d2b7439957da3b1a35fab9596ef693829](https://github.com/SRI-CSL/langlearn/commit/46e8cc7d2b7439957da3b1a35fab9596ef693829).
