### ISSUE TITLE
Change Default Domain for Production 

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#25]
The default server domain needs to be:
lingoboost.csl.sri.com

The current lingoboost-dev.csl.sri.com will remain as a user-input option for server selection (e.g., user = "user@lingoboost-dev.csl.sri.com").

**Comment by bcooper94** [comment]
Changed default server to "user@lingoboost.csl.sri.com" as per Tim's change to the production server domain in commit [46e8cc7d2b7439957da3b1a35fab9596ef693829](https://github.com/SRI-CSL/langlearn/commit/46e8cc7d2b7439957da3b1a35fab9596ef693829).
