### ISSUE TITLE
Remove White Noise Fade In/Out

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#26]
The current white noise has a fade in and fade out built in (bnoise3.ogg) that should not be present.

The white noise should be a constant volume and not changing.

**Comment by bcooper94** [comment]
Fixed with commit [488566d5d8d8fecdb7c7be4800f2c630df0b689b](https://github.com/SRI-CSL/langlearn/commit/488566d5d8d8fecdb7c7be4800f2c630df0b689b).

**Comment by sanchezdanj** [comment]
With hesitancy, I re-open this so we can revert back to the previous white noise file that had the ramp in and ramp down to deal with the gap skip issue in Android.

**Comment by AddictArts** [comment]
Completed and in release 1.3.0
