### ISSUE TITLE
Volume Set Warning on Volume Page

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#28]
Currently, the user cannot continue past the Volume Setting (for sleep or test) without setting the volumes first. However, there is no language on that page that clearly states this requirement, which can lead to confusion.

Fix: Include text directly below "Sleep/Test Volume" that states:
You must adjust the volume before you can proceed.

**Comment by bcooper94** [comment]
Added in version 0.34.
