### ISSUE TITLE
White Noise Dampening during Word Presentation

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#31]
During the Sleep Session, to make the words more audible, we need to ramp down the volume when the word starts (or shortly before, ~250ms) and ramp back up afterwards.

The amount that the white noise should ramp down should be a percentage of the user-chosen value for the white noise. This value should default to 30 percent, and be taken as a variable from the server. The server will send along the value as an INTEGER with the variable name, "volume_dampening"
e.g., volume_dampening : 30

As an example, if the device/system volume is set to 80, white noise is set to 50, and word volume is set to 40, when a word is presented, the white noise volume should be 15 ((volume_dampening/100)*WhiteNoise_Volume); ((30/100)*50).

**Comment by bcooper94** [comment]
Added in build 0.37.
