### ISSUE TITLE
Stop Stimulation after N seconds from start of Sleep Session

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#32]
To prevent stimulating when the participant wakes up, and in later stages of sleep, the client should STOP word presentation after a fixed duration of time after the Sleep Session is started.

This value will be passed from the server to the client as such:
stimulation_stop : 18000

The value is an INTEGER in seconds the start of the sleep session. If the elapsed time is longer than the "stimulation stop" value, then the system should stop presenting words.

**Comment by bcooper94** [comment]
@sanchezdanj I take it 18000 is the default value if the server does not return a "stimulation_stop" property?

**Comment by AddictArts** [comment]
Short of testing it looks like @bcooper94 got this completed and it is part of 0.37
