### ISSUE TITLE
Log Activity Lifecycle Events

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#33]
We need to log all relevant interactions in the Test and Sleep logs to ensure we have an accurate representation of the user's behavior. 

@bcooper94 and I discussed logging the “pause” events, but @tim-mccarthy suggested that we log all activity lifecycle events. This would likely cover other interactions, such as implicit "pause" events that are triggered by switching between apps or hitting the home button.

For any of these logs, we should incorporate them into the standard sleep and test logs, and introduce a unique token to separate them out for simple parsing. e.g., in the Sleep Log, we can use put this data into the "word" column in the data file and use a string like user.event.Pause, user.event.Quit, user.event.Stop...etc.

**Comment by bcooper94** [comment]
@sanchezdanj The only problem I see with logging all lifecycle activity events, include system ones, is that the user quitting sleep mode, for example, will trigger the onPause, onStop, then onDestroy in quick succession. These system events can also be triggered without user interaction: if the system is running low on memory, it can trigger the onDestroy event to reclaim memory. Should we just log user events, such as hitting the back button, Quit button, or Pause button?

**Comment by tim-mccarthy** [comment]
@bcooper94 I think it would be worthwhile to log system-triggered events as well. If we get OOM-killed halfway through the night, it would be worthwhile to see that when investigating why a user's log doesn't show as much data as we were hoping for.

**Comment by sanchezdanj** [comment]
Unless we think the file size will get too large (I can't imagine), we want as much data as we can get.  As long as all the events have a specific token (user.eventActivity.<> or system.eventActivity.<>) we can very easily parse them out for analysis.

**Comment by bcooper94** [comment]
Ok, that seems reasonable. I don't see the log growing very large in any reasonable use case, and even if the user spams a button, it would grow pretty slowly.

**Comment by sanchezdanj** [comment]
User spamming would actually be a really good indicator of something being wrong as well!

**Comment by bcooper94** [comment]
Added in version 1.0.
