### ISSUE TITLE
Separate the Start Sleep Delay from Pause Delay

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#38]
Rather than just a single "start_delay" parameter, we want to separate this out to two values for when the session starts and when the session pauses due to activity/user-pausing.

All these parameters will be passed from the server, and should have a default as well.

Per #35, we want "session_start_delay" to be the delay when Sleep first starts, and have it set to 1800 seconds.
We want "pause_delay" to be the delay that happens DURING a sleep session, and have it set to 300 seconds.

**Comment by AddictArts** [comment]
@sanchezdanj  @tim-mccarthy fyi These need to be implemented on the backend. The client nearly has support completed. Coming in next build.

**Comment by AddictArts** [comment]
Completed and in 1.2.0 when that is released shortly
