### ISSUE TITLE
Logging Sleep Time in Sham

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#40]
Currently, because there are no events in the Sham, we can lose how long the app was running if there isn't a final event.Close or something else.

**Comment by AddictArts** [comment]
@sanchezdanj there is an event I am seeing logged and that is onStop.  If they background the app. There is user Stop and the onStop if the quit and then exit the app (background etc it). These are sent to the server. Can we close this?

**Comment by sanchezdanj** [comment]
@AddictArts I'm going to leave it open until we test the new Sham condition after addressing #41. I believe that you are correct, that the system events should be fine for tracking sleep time, but all of the data we have right now for Sham has words that were played, likely due to the bug listed in #41. Once we verify a full "sham" log with no words that is able to show the full sleep time, I will close this out.

**Comment by sanchezdanj** [comment]
SHAM Sleep Log Successful: Closing.
