### ISSUE TITLE
Center Align "Welcome to LingoBoost" on Main Menu

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#44]
Welcome to LingoBoost is not center aligned on the main menu - although I believe it is during the user-entry.

Please center align.

**Comment by AddictArts** [comment]
Replaced the "Welcome ..." with a new banner image and it is centered in both the user choice activity and the main activity.

**Comment by sanchezdanj** [comment]
The current screenshots looks great.

![image001](https://user-images.githubusercontent.com/6577692/32380349-1c5d7450-c06d-11e7-9748-d1a0bad3613f.png)
