### ISSUE TITLE
Test Trial Skip

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#54]
We need to add a “Don’t Know” option during test for each trial, for when people need to skip a question.

In addition to the “Submit” option for each trial, there needs to be an option to Skip/Pass, particularly for the pre-test when people are not expected to know.

- Maybe have it right-aligned to "Submit", or under it with enough space to avoid accidental presses.
- Mark this response in the test log with a “trial.skip” in the response column, similar to how system events are logged.

**Comment by AddictArts** [comment]
This is part of version 1.4.0 that is pending release.
