### ISSUE TITLE
Sleep Session: Notify of Connectivity Issues

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#55]
We need to notify people during the sleep session when the app cannot connect to the server due to internet connectivity problems. 

Currently, it just pops up a screen and goes back to the menu quickly. It's too easy for a participant to start the sleep session, and ignore the phone and miss the sleep session quitting out.

Can we have it hang on that error page and play the following sound ONCE when the page is first displayed?

[error_blips.ogg.zip](https://github.com/SRI-CSL/langlearn/files/1477002/error_blips.ogg.zip)

**Comment by AddictArts** [comment]
@sanchezdanj  Yes it can do that. Brandon and I felt the communication with the server should happen at the main activity, but this would require a significant refactor, a phew days or week of work possibly. And all testing to this point would be quote invalidated end quote if refactored.

**Comment by sanchezdanj** [comment]
@AddictArts , just to clarify.
1) We can *easily* make the connectivity page hang and add the sound.
2) You suggest that the connectivity check (communication w/ server) and updating should be happening when the app first launches, but this would require a large refactor.

**Comment by AddictArts** [comment]
@sanchezdanj yes on #1 and #2. #1 is now implemented. I'm testing it.

**Comment by AddictArts** [comment]
In version 1.4.0, which is ready for release very soon
