### ISSUE TITLE
Test Feedback?

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#7]
This feature is desired, but not a critical add-on until we ensure that the system of data logging and uploading is rock solid.
> Add translation feedback during the "Word Test" component. 
- System presents word text and plays word sound
- User responds to word, presses Submit/Enter
- System presents word again, and displays all possible English translations, with a "Continue" button to advance to next word

> How to make this happen?
- The backend client, when grabbing the word list, would also run private_data.get_translations() to store the translation information. This data is an n-item length list with 1 through n possible translations for each item. This list would accompany each of the foreign words.
- The frontend client, when displaying feedback, would present the sound file once again, and then display an enumerated feedback list that is scaled to hit (max size is current text size, min size is scaled to fit enumerated list) with a continue button at the bottom right.

**Comment by tim-mccarthy** [comment]
The backend now includes a list of translations with each words.

**Comment by AddictArts** [comment]
How do we activate this feature:
* is it a setting, boolean on or off
* is it a new main menu choice with sleep and test
* is it the default?

**Comment by tim-mccarthy** [comment]
A new boolean parameter in the JSON, "feedback", would probably be the cleanest option.

As far as the other details, I defer to Danny.

**Comment by sanchezdanj** [comment]
Per Tim, this will be handled in the JSON. We will default to "ON." That's a great solution as long as it's an easy parameter to pass along.

**Comment by AddictArts** [comment]
This is completed and released in 0.28
