### ISSUE TITLE
App Behavior when Internet is Not Available

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#9]
We should determine what the app should do when the internet is not available.

**Comment by AddictArts** [comment]
I had added support for this earlier, so it is in the app. It currently will say "Unable to resolve host...". I easily change it to a nice message like system unavailable at this time, please try again later

**Comment by sanchezdanj** [comment]
We should probably make it say something like "No Internet Available. Please connect to the internet and try again"

**Comment by AddictArts** [comment]
Will be part of 0.16
